istio/old_pilot_repo

BUILD, model/registry.go, model/validation.go, platform/kube/client.go, platform/kube/controller.go, platform/kube/minikube_test.go, platform/kube/queue.go, platform/kube/queue_test.go, test/mocks.go, test/mocks_test.go
* Use cache for registry
* Extensible chained handlers
* Optimize Update event
=> Cached registry and controller interface

model/registry.go, platform/kube/client.go, platform/kube/config.go, platform/kube/controller.go, platform/kube/minikube_test.go, test/mocks.go
There's a 10 second lag between a request to create a TPR and TPR endpoints being active.
Added error out to List call.
=> Add TPR existence check

proxy/envoy/discovery.go
Adds a basic CDS API as described here: https://github.com/lyft/envoy/issues/144#issuecomment-267191173. Doesn't effect other functionality.
Note that CDS has not been added to Envoy yet.
=> Add a simple CDS API.

model/controller.go, model/service.go, platform/kube/BUILD, platform/kube/controller.go, platform/kube/kube_test.go, proxy/envoy/discovery.go
=> Add a method to query instances by IP

README.md, cmd/BUILD, cmd/main.go, model/service.go, platform/kube/controller.go, proxy/envoy/agent.go, proxy/envoy/config.go, proxy/envoy/resources.go, proxy/envoy/watcher.go, test/example/echo/Dockerfile, test/example/echo/Dockerfile-init, test/example/echo/Dockerfile-manager, test/example/echo/Dockerfile-mixer, test/example/echo/build.sh, test/example/echo/echo.yaml, test/example/echo/server_config.pb.txt
Added traffic capture with an init container.
=> Server-side configuration for Envoy with iptables

.gitignore, README.md, bin/bazel_to_go.py
Added a script to convert WORKSPACE file to vendor/ directory to be used by the go tooling.
Based on @mandarjog's script from mixer.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/istio/manager/48)
=> Provide tools and instructions how to use go tool

.bazelrc.jenkins, .gitignore, Jenkinsfile, bin/bazel_to_go.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/istio/manager/54)
=> Added simple Jenkinsfile for presubmits

WORKSPACE, cmd/manager/main.go, docker/BUILD, proxy/envoy/agent.go, proxy/envoy/config.go, proxy/envoy/watcher.go, test/client/BUILD, test/client/client.go, test/integration/BUILD, test/integration/http-service.yaml.tmpl, test/integration/manager.yaml.tmpl, test/integration/templater.go, test/integration/test.sh, test/server/BUILD, test/server/echo.go
Added test client, server, better template, better test script, and packaging bazel rules.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/istio/manager/55)
=> Improvement to test infrastructure

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/istio/manager/58)
=> Updates Jenkinsfile with stages

cmd/manager/main.go, test/integration/driver.go, test/integration/http-service.yaml.tmpl
Checks that Manager and Proxy can operate in a multi-namespace cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/istio/manager/63)
=> Use a flag for a test namespace

model/controller.go, model/service.go, model/service_test.go, model/validation.go, platform/kube/controller.go, platform/kube/kube_test.go, proxy/envoy/BUILD, proxy/envoy/config.go, proxy/envoy/config_test.go, proxy/envoy/watcher.go
PR removes "Namespace" from Istio service, and instead uses fully qualified "Hostname" property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/istio/manager/66)
=> Use hostname in the service model abstraction

WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/istio/manager/69)
=> Rebase Istio proxy

docker/BUILD, docker/prepare_proxy.sh, test/integration/http-service.yaml.tmpl
Partially addresses #36 and #65
=> Move proxy iptable configuration into istio init image

doc/proxy-injection.md, doc/proxy-redirection-configuration.md
Summarization of discussion at https://github.com/istio/manager/issues/36 for "IP table rules for a single port deployment".
=> Document proxy injection and configuration method

proxy/envoy/config.go, proxy/envoy/resources.go
Adds support for routing based on match headers.
=> Header based routing.

proxy/envoy/config.go
Reads fault rules from the routing rule spec and sets up fault injection filters in Envoy.
=> fault injection filter for envoy config

proxy/envoy/config.go
Switched to generating services based on routing rules instead of upstream definitions.
=> Refactor cluster generation

proxy/envoy/config.go, proxy/envoy/policy.go, proxy/envoy/resources.go, proxy/envoy/route.go
We need a follow up PR with mixer deployment and mixer address passed to manager.
=> Add mixer filter back

model/registry.go, model/service.go, proxy/envoy/config.go, proxy/envoy/policy.go
Example how to do policy application.
=> Apply load balancing policy

proxy/envoy/config.go, proxy/envoy/policy.go, test/client/client.go, test/integration/BUILD, test/integration/driver.go, test/integration/policy-fault-injection.yaml.tmpl
Will add testing in the next pass. I have to rework my test suite after @ayj 's changes.
=> Fault filter

Jenkinsfile, proxy/envoy/config.go, proxy/envoy/policy.go, test/client/client.go, test/integration/BUILD, test/integration/driver.go, test/integration/policy-fault-injection.yaml.tmpl
This PR will be merged automatically once checks are successful.
=> DO NOT MERGE! Fast Forward stable to d19498afd05cc3419bd6cc402146a4c0903b9974.

proxy/envoy/config.go, proxy/envoy/route.go
=> Add pod IP as a virtual host entry

bin/e2e.sh, test/integration/BUILD, test/integration/driver.go, test/integration/mixer.yaml.tmpl
1. Add mixerTag
2. Only delete namespaces that we create
3. Add `--skipBuild` option to e2e.sh
=> Add default tag for mixer

WORKSPACE
=> Rebase proxy

platform/kube/BUILD, platform/kube/controller.go, platform/kube/controller_test.go
=> Ingress controller: add support for ingress class annotation

WORKSPACE, bin/check.sh, bin/init.sh, docker/BUILD
Run buildifer on bazel files and fixe issues found.
=> Enable buildifer checks

model/config_test.go, model/conversion.go
All tests are currently in config_test.go which is not ideal. Now that we have good test coverage in model package I'll work on a follow-up PR to move things around into more sensible file locations.
=> Increase model package test coverage to 97.5%

cmd/istioctl/istioctl_test.go, cmd/istioctl/main.go, cmd/istioctl/testdata/invalid-dest-policy.yaml, cmd/istioctl/testdata/rule-content-route.yaml
I noticed when debugging yesterday that invalid YAML was being ignored by _istioctl_.  See https://github.com/istio/manager/issues/281
=> Use istio/manager/model/conversion FromJSON

Jenkinsfile, cmd/istioctl/BUILD, cmd/istioctl/istioctl_test.go, cmd/istioctl/main.go, doc/istioctl.md
For issue #298 .  @frankbu This one is for you ... feel free to review it.
=> Support for multi-name delete and name-from-yaml-file delete

proxy/envoy/resources.go
See https://github.com/istio/manager/issues/307
=> Fix ingress omitempty bug

model/config.go, model/config_test.go, platform/kube/controller_test.go
Fixes #262 
Also:
* make unit test more realistic by using names instead of kinds
=> Sort route rules in a stable manner

.bazelrc.jenkins, Jenkinsfile
=> External cluster for postsubmit

proxy/envoy/policy.go, proxy/envoy/testdata/envoy-fault.json.golden, proxy/envoy/testdata/envoy-v0.json.golden, proxy/envoy/testdata/envoy-v1.json.golden, test/integration/mixer.yaml.tmpl
Supply source and target service names to Mixer.
=> Add service attributes to Mixer

proxy/envoy/resources.go, test/integration/ingress-proxy.yaml.tmpl
Removes `omitempty` from the cluster_manager clusters field. Resolves https://github.com/istio/manager/issues/307
=> Resolve no ingress rule bug

proxy/envoy/config.go, proxy/envoy/ingress.go, proxy/envoy/resources.go
Get rid of sorting struct since it creates coverage loss noise.
=> Use slice sort for hosts

Jenkinsfile, bin/e2e.sh, cmd/istioctl/inject.go, docker/BUILD, platform/kube/inject/inject.go, platform/kube/inject/inject_test.go, platform/kube/inject/testdata/enable-core-dump.yaml.injected, platform/kube/inject/testdata/frontend.yaml.injected, platform/kube/inject/testdata/hello-multi.yaml.injected, platform/kube/inject/testdata/hello.yaml.injected, platform/kube/inject/testdata/multi-init.yaml.injected, test/integration/driver.go, test/integration/egress-proxy.yaml.tmpl, test/integration/ingress-proxy.yaml.tmpl, test/integration/manager-discovery.yaml.tmpl
=> Split "runtime" image into "proxy" and "manager"

Jenkinsfile
- No need to run linter and other as code does not change
- Triggering fast forward as last step of POSTSUBMIT stage.
=> Adds a faster regression suite for manager deps.

cmd/manager/main.go, model/controller.go
=> Separate discovery and apiserver

model/service.go, platform/kube/controller.go, proxy/envoy/discovery.go, proxy/envoy/ingress_test.go, proxy/envoy/testdata/all-cds.json.golden, proxy/envoy/testdata/all-rds.json.golden, proxy/envoy/testdata/all-sds.json.golden, test/mock/service.go, test/mock/service_test.go, test/util/diff.go
- add comments
- skip external services from all-* requests
- remove mock instances for external services
=> Minor cleanup of egress & all RDS code

cmd/manager/main.go, proxy/envoy/BUILD, proxy/envoy/config_test.go, proxy/envoy/config_test.sh, proxy/envoy/egress.go, proxy/envoy/egress_test.go, proxy/envoy/ingress.go, proxy/envoy/ingress_test.go, proxy/envoy/resources.go, proxy/envoy/testdata/egress-envoy.json.golden, proxy/envoy/testdata/envoy-fault.json.golden, proxy/envoy/testdata/envoy-v0-auth.json.golden, proxy/envoy/testdata/envoy-v0.json.golden, proxy/envoy/testdata/envoy-v1-auth.json.golden, proxy/envoy/testdata/envoy-v1.json.golden, proxy/envoy/testdata/ingress-envoy-partial-ssl.json.golden, proxy/envoy/testdata/ingress-envoy-ssl.json.golden, proxy/envoy/testdata/ingress-envoy.json.golden, tools/bazel.rc
Bazel test to spawn envoy with golden config, wait a second, and kill it.
=> Add envoy config test run

WORKSPACE, model/config_test.go, model/validation.go, proxy/envoy/resources.go, proxy/envoy/route.go, proxy/envoy/testdata/rds-timeout.json.golden, proxy/envoy/testdata/timeout-route-rule.yaml.golden
Corresponding to PR https://github.com/istio/api/pull/76
=> add per-retry timeout support to route rules

Jenkinsfile, bin/e2e.sh, test/integration/driver.go, test/integration/infra.go, test/integration/ingress.go, test/integration/reachability.go, test/integration/routing.go, test/integration/testdata/ingress.yaml
=> More improvements to e2e

WORKSPACE, bin/e2e.sh, bin/init.sh, test/client/BUILD, test/client/client.go, test/grpcecho/BUILD, test/grpcecho/echo.proto, test/integration/BUILD, test/integration/access.go, test/integration/driver.go, test/integration/egress.go, test/integration/grpc.go, test/integration/infra.go, test/integration/ingress.go, test/integration/reachability.go, test/integration/routing.go, test/integration/tcp.go, test/integration/testdata/app.yaml.tmpl, test/server/BUILD, test/server/echo.go
More work on test framework and add reachability tests for GRPC.
Extend test client and server with an echo GRPC service.
#533
=> HTTP/2 (GRPC) tests

test/integration/access.go, test/integration/egress.go, test/integration/infra.go
=> Improve error message on missing pod

WORKSPACE, platform/kube/ingressstatus.go
Should enable the ingress status syncer to obtain the load balancer IP address.
=> Ingress status publish service

WORKSPACE, proxy/envoy/policy.go, proxy/envoy/resources.go, proxy/envoy/testdata/envoy-fault.json.golden, proxy/envoy/testdata/envoy-v0-auth.json.golden, proxy/envoy/testdata/envoy-v0.json.golden, proxy/envoy/testdata/envoy-v1-auth.json.golden, proxy/envoy/testdata/envoy-v1.json.golden
Also updates WORKSPACE to include ratelimit proxy fix
Co-Authored-By: ZackButcher <zack.butcher@gmail.com>
=> Populate the `quota_name` parameter of the proxy's config

cmd/manager/main.go
This should solve istio/istio#166
=> Disable sidecar agent from reading ingress resources

proxy/agent.go, proxy/agent_test.go, proxy/envoy/watcher.go
=> Proxy agent: panic after retries, broadcast abort, minor fixes

WORKSPACE
=> update to use PROXY image with crash bug fix

cmd/istioctl/main.go
Addresses point 2 in
https://github.com/istio/istio.github.io/issues/91
=> Fixing error message typo

proxy/envoy/discovery.go
For for issue #615 .  Simplifies implementation of ListAllClusters.
=> Combine duplicated code in ListClusters and ListAllClusters

WORKSPACE, bin/init.sh, model/config.go, model/config_test.go, model/validation.go, model/validation_test.go, platform/kube/conversion.go, platform/kube/ingressstatus.go, proxy/envoy/discovery.go, proxy/envoy/egress.go, proxy/envoy/header.go, proxy/envoy/policy.go, proxy/envoy/testdata/cb-policy.yaml.golden
Needs a follow-up to validate destination policy name against the destination field value.
As-is sufficient to pass the tests with no functional change.
=> Update config proto for destination policy

client/proxy/BUILD, client/proxy/proxy.go
Add logging of HTTP traffic from istioctl to the Discovery Manager
=> Add logging of HTTP traffic

cmd/istioctl/main.go, cmd/manager/main.go
This fixes Issue #653 
The informers weren't being started.
In testing, after the GET operation worked, it returned incorrect output so I fixed that as well.
=> Start the informers so the get and list functions work

apiserver/handler.go, client/proxy/proxy.go
Signed-off-by: Liam White <liamwhite@uk.ibm.com>
=> Add logging to the apiserver

apiserver/handler.go, cmd/istioctl/main.go
Signed-off-by: Liam White <liamwhite@uk.ibm.com>
=> Add more logging to the apiserver and istioctl

model/validation.go, model/validation_test.go, proxy/envoy/BUILD, proxy/envoy/header.go, proxy/envoy/header_test.go, proxy/envoy/ingress.go, proxy/envoy/route.go
=> Header validation

platform/kube/client.go
Manager and mixer API server paths are not consistent. Manager path is
prefixed with Istio resource version (i.e. v1alpha1) and mixer path is
not. Short term workaround is to special case this behavior. Long term
solution is to unify API scheme and server implementations.
See https://github.com/istio/api/issues/94 for long term tracking.
=> istioctl: Fix path for Mixer Config server

cmd/istioctl/BUILD, proxy/envoy/BUILD, proxy/envoy/discovery_test.go, proxy/envoy/watcher.go, proxy/envoy/watcher_test.go
Minor: trigger proxy restart by default without notifications
=> Fix drain duration bug (again)

test/integration/ingress.go, test/integration/routing.go, test/integration/testdata/rule-content-route.yaml.tmpl, test/integration/testdata/rule-default-route.yaml.tmpl, test/integration/testdata/rule-fault-injection.yaml.tmpl, test/integration/testdata/rule-redirect-injection.yaml.tmpl, test/integration/testdata/rule-regex-route.yaml.tmpl, test/integration/testdata/rule-weighted-route.yaml.tmpl, test/integration/testdata/zipkin.yaml
Quick dumb check + some minor refactoring.
=> Test regex header routing

apiserver/apiserver.go, apiserver/apiserver_test.go, apiserver/handler.go
Adds the endpoint described by #609 
Signed-off-by: Liam White <liamwhite@uk.ibm.com>
=> API server healthcheck endpoint

cmd/istioctl/mixer.go
=> istioctl mixer create should output success/failure and reason

WORKSPACE
This allows to build and unit test manager natively on mac.
=> Fix native mac build

proxy/agent.go, proxy/agent_test.go
=> Bug fix: correct restart delay duration in proxy agent

doc/service-registry.md
There were some repeated words.
=> Fixed repeated words

cmd/istioctl/main.go, proxy/envoy/cert.go, proxy/envoy/cert_test.go
=> print no resources found, use path.Join

cmd/manager/main.go, platform/kube/controller.go, platform/kube/controller_test.go, platform/kube/conversion.go, platform/kube/conversion_test.go, test/integration/apiserver.go
Allow a different DNS domain suffix than "cluster.local"
=> Make domain suffix configurable

Jenkinsfile
As @mandarjog pointed out. We should check the version we get from curl.
=> Adds a check on version

proxy/agent.go, proxy/agent_test.go
=> Fix cascading aborts

doc/proxy-controller.md
The file https://github.com/istio/api/blob/master/proxy/v1/config/cfg.md no longer exists
=> Update proxy-controller.md schema link

model/config.go
cherry-pick bug fix from release-0.1 branch
=> fix match rule discarded from ingress routes (#897)

model/config.go, proxy/envoy/discovery.go
=> Correct the sds data structure

test/integration/testdata/egress-proxy.yaml.tmpl, test/integration/testdata/rbac-beta.yaml.tmpl
Fixes last part of istio/istio#418
=> Add RBAC for Egress

.gitignore, bin/gazelle, model/service.go, platform/kube/BUILD, platform/kube/cache.go, platform/kube/cache_test.go, platform/kube/controller.go, platform/kube/controller_test.go, proxy/envoy/discovery.go
=> Add kube support for availability zones

prow/pilot-postsubmit.sh, prow/pilot-presubmit.sh
This depends on https://github.com/istio/test-infra/pull/349
=> Update kube config

Jenkinsfile, bin/push-docker
- Update bin/push-docker to take multiple tags
- Re-enable istioctl builds as well as stable artifacts creation for release.
=> Enable istioctl build by Jenkins

.gitignore, docker/prepare_proxy_test.yaml, platform/kube/inject/inject.go, platform/kube/inject/testdata/auth.cert-dir.yaml.injected, platform/kube/inject/testdata/auth.non-default-service-account.yaml.injected, platform/kube/inject/testdata/auth.yaml.injected, platform/kube/inject/testdata/enable-core-dump.yaml.injected, platform/kube/inject/testdata/frontend.yaml.injected, platform/kube/inject/testdata/hello-config-map-name.yaml.injected, platform/kube/inject/testdata/hello-multi.yaml.injected, platform/kube/inject/testdata/hello-probes.yaml.injected, platform/kube/inject/testdata/hello.yaml.injected, platform/kube/inject/testdata/multi-init.yaml.injected, platform/kube/inject/testdata/statefulset.yaml.injected, test/integration/testdata/app.yaml.tmpl, test/integration/testdata/ca.yaml.tmpl, test/integration/testdata/egress-proxy.yaml.tmpl, test/integration/testdata/ingress-proxy.yaml.tmpl, test/integration/testdata/mixer.yaml.tmpl, test/integration/testdata/pilot.yaml.tmpl, test/integration/testdata/zipkin.yaml
Fixes https://github.com/istio/istio/issues/441
(Manual adjustments to not touch files where trailing newline is
missing + manual change of go file)
=> git ls-files|xargs sed -i .bak -e 's/PullPolicy: Always/PullPolicy: IfNotPresent/g'

platform/kube/inject/inject.go, platform/kube/inject/testdata/auth.cert-dir.yaml.injected, platform/kube/inject/testdata/auth.non-default-service-account.yaml.injected, platform/kube/inject/testdata/auth.yaml.injected, platform/kube/inject/testdata/enable-core-dump.yaml.injected, platform/kube/inject/testdata/frontend.yaml.injected, platform/kube/inject/testdata/hello-config-map-name.yaml.injected, platform/kube/inject/testdata/hello-multi.yaml.injected, platform/kube/inject/testdata/hello-probes.yaml.injected, platform/kube/inject/testdata/hello.yaml.injected, platform/kube/inject/testdata/multi-init.yaml, platform/kube/inject/testdata/multi-init.yaml.injected, platform/kube/inject/testdata/statefulset.yaml.injected
Fixes: #631 istio/istio#345
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
=> Move initContainers from annotations to spec

model/service.go, model/service_test.go, proxy/envoy/ingress.go, test/client/client.go, test/integration/ingress.go, test/integration/testdata/ingress.yaml, test/server/echo.go
Fixes #925 for insecure gRPC. Will add transport security in a subsequent PR.
=> Add gRPC support to ingress

cmd/istioctl/inject.go, platform/kube/inject/inject.go, platform/kube/inject/inject_test.go, platform/kube/inject/testdata/auth.cert-dir.yaml.injected, platform/kube/inject/testdata/auth.non-default-service-account.yaml.injected, platform/kube/inject/testdata/auth.yaml.injected, platform/kube/inject/testdata/enable-core-dump.yaml.injected, platform/kube/inject/testdata/frontend.yaml.injected, platform/kube/inject/testdata/hello-always.yaml.injected, platform/kube/inject/testdata/hello-config-map-name.yaml.injected, platform/kube/inject/testdata/hello-multi.yaml.injected, platform/kube/inject/testdata/hello-never.yaml.injected, platform/kube/inject/testdata/hello-probes.yaml.injected, platform/kube/inject/testdata/hello.yaml.injected, platform/kube/inject/testdata/multi-init.yaml.injected
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
Fixes: #989
=> Add imagePullPolicy flag to istioctl and kube platform

doc/testing.md
Doc update for how to build Docker images.
=> Fix build command for Docker images.

bin/init.sh
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
=> Ensure expected GOPATH setup in the init script

WORKSPACE, docker/Dockerfile.proxy, docker/Dockerfile.proxy_debug
https://github.com/istio/proxy/commit/2a8426631283669ef1a433c5d1bb84642f042e81
=> updating to match new debug image

platform/kube/conversion.go, platform/kube/conversion_test.go
=> Sort serviceaccounts in service model.

proxy/envoy/config.go, proxy/envoy/egress.go, proxy/envoy/ingress.go, proxy/envoy/mixer.go, proxy/envoy/resources.go, proxy/envoy/testdata/lds-v0-fault-auth.json.golden, proxy/envoy/testdata/lds-v0-fault.json.golden, proxy/envoy/testdata/lds-v0-none-auth.json.golden, proxy/envoy/testdata/lds-v0-none.json.golden, proxy/envoy/testdata/lds-v0-weighted-auth.json.golden, proxy/envoy/testdata/lds-v0-weighted.json.golden, proxy/envoy/testdata/lds-v1-fault-auth.json.golden, proxy/envoy/testdata/lds-v1-fault.json.golden, proxy/envoy/testdata/lds-v1-none-auth.json.golden, proxy/envoy/testdata/lds-v1-none.json.golden, proxy/envoy/testdata/lds-v1-weighted-auth.json.golden, proxy/envoy/testdata/lds-v1-weighted.json.golden, proxy/envoy/testdata/rds-ingress-ssl.json.golden, proxy/envoy/testdata/rds-ingress-weighted.json.golden, proxy/envoy/testdata/rds-ingress.json.golden, tools/bazel.rc
+ small change to forward attributes in ingress
=> Enable TCP mixer check

proxy/envoy/resources.go
sometimes it's nice to get the full name out there, with all these xDS
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> resources: clarify acronyms

test/integration/driver.go
=> add help string for invalid e2etest

.github/PULL_REQUEST_TEMPLATE.md, OWNERS
Add files for mungegithub. 
Here is a refer: https://github.com/istio/mixer/pull/1024
=> Init OWNERS and pr template

proxy/envoy/discovery_test.go, proxy/envoy/testdata/lds-v0-fault-nomixer.json.golden, proxy/envoy/testdata/lds-v0-none-nomixer.json.golden, proxy/envoy/testdata/lds-v0-weighted-nomixer.json.golden, proxy/envoy/testdata/lds-v1-fault-nomixer.json.golden, proxy/envoy/testdata/lds-v1-none-nomixer.json.golden, proxy/envoy/testdata/lds-v1-weighted-nomixer.json.golden, proxy/envoy/testdata/rds-v0-nomixer.json.golden
Add regressions tests for mixerless pilot.
```release-note
NONE
```
=> Tests with no mixer

Makefile
=> Introduced `make gazelle` to pilot.

WORKSPACE, adapter/config/crd/client.go, adapter/config/crd/controller.go, adapter/config/ingress/controller.go, bin/fmt.sh, bin/use_bazel_go.sh, cmd/istioctl/inject.go, cmd/istioctl/mixer.go, cmd/sidecar-initializer/main.go, platform/consul/conversion_test.go, platform/eureka/controller.go, platform/eureka/conversion.go, platform/eureka/servicediscovery.go, platform/kube/client.go, platform/kube/controller.go, platform/kube/controller_test.go, platform/kube/conversion.go, platform/kube/conversion_test.go, platform/kube/inject/initializer.go, platform/kube/inject/initializer_test.go, proxy/context.go, proxy/envoy/fault.go, test/client/client.go, test/integration/access.go, test/integration/infra.go, test/integration/zipkin.go, test/mock/secret_test.go, test/server/echo.go
```release-note
None
```
Fixed https://github.com/istio/pilot/issues/1077
/cc @ldemailly
=> Introduced `make fmt` to pilot.

Makefile
=> Enabled racetest for pilot.

platform/kube/inject/BUILD, proxy/envoy/BUILD
=> Updated two BUILD files for pilot based on bin/gazelle.

Makefile
```release-note
none
```
/cc @rshriram
=> Added `make fmt` to pilot Makefile.

platform/eureka/servicediscovery_test.go
Fixes https://github.com/istio/pilot/issues/1070
=> Fix Eureka testing flakiness

platform/kube/inject/inject.go, platform/kube/inject/testdata/auth.cert-dir.yaml.injected, platform/kube/inject/testdata/auth.non-default-service-account.yaml.injected, platform/kube/inject/testdata/auth.yaml.injected, platform/kube/inject/testdata/daemonset.yaml.injected, platform/kube/inject/testdata/enable-core-dump.yaml.injected, platform/kube/inject/testdata/frontend.yaml.injected, platform/kube/inject/testdata/hello-always.yaml.injected, platform/kube/inject/testdata/hello-config-map-name.yaml.injected, platform/kube/inject/testdata/hello-multi.yaml.injected, platform/kube/inject/testdata/hello-never.yaml.injected, platform/kube/inject/testdata/hello-probes.yaml.injected, platform/kube/inject/testdata/hello.yaml.injected, platform/kube/inject/testdata/job.yaml.injected, platform/kube/inject/testdata/multi-init.yaml.injected, platform/kube/inject/testdata/multiple-initializer.yaml.injected, platform/kube/inject/testdata/replicaset.yaml.injected, platform/kube/inject/testdata/replicationcontroller.yaml.injected, platform/kube/inject/testdata/required.yaml.injected, platform/kube/inject/testdata/single-initializer.yaml.injected, platform/kube/inject/testdata/statefulset.yaml.injected
Fixing https://github.com/istio/pilot/issues/1083.
```release-note-none
```
=> added sidecar command to proxy command

WORKSPACE, platform/eureka/servicediscovery_test.go
And fixing go format error
```release-note
none
```
=> Updating cobra (to get Args:  cobra.MinimumNArgs etc)

WORKSPACE, docker/Dockerfile.proxy, docker/Dockerfile.proxy_debug, test/integration/driver.go
The updated proxy has support for WebSockets, more flexible zipkin traces (compatible with Jaeger, etc.).
=> updating proxy sha everywhere

WORKSPACE, prow/pilot-postsubmit.sh
After a PR on master is merged and passes postsubmit, its commit is consider stable and the stable branch should be fast forwarded to this commit.
```release-note
None
```
=> Fast forward pilot/stable after postsubmit

doc/build.md
The current build instructions are too lengthy, confusing and contain too much information. Make the instructions short.
```NONE
```
=> rewrite build instructions

test/integration/testdata/initializer-configmap.yaml.tmpl
"Off" without quote will be treated as false, so we need to make
sure the injection policy config parameters include a quote so
that we can handle "off" well.
Check here for detail about "off": http://yaml.org/type/bool.html
```release-note
NONE
```
/cc @ayj
=> Added quote for inject policy config.

bin/init.sh
=> Fix bad requirement for GOPATH to be set

doc/testing.md
Update instructions for setting up development clusters on GKE and minikube.
```release-note
```
=> Update instructions for creating development clusters

WORKSPACE, docker/Dockerfile.proxy, docker/Dockerfile.proxy_debug
=> Update proxy sha to bf6e90.

platform/eureka/serviceaccounts.go
=> Copyright fix

bin/e2e.sh, bin/gocompile-and-push-images.sh
The same rationale as in https://github.com/istio/pilot/pull/1114
The scripts fail in Hebrew locale.
```NONE
```
=> fix format of a local tag of docker images in scripts

WORKSPACE, docker/Dockerfile.proxy, docker/Dockerfile.proxy_debug
=> proxy update

prow/pilot-e2e-smoketest.sh
```release-note
None
```
Preparation: https://github.com/istio/test-infra/pull/473
Refer: https://github.com/istio/mixer/pull/1234
=> Run rbac-no_auth e2e test

doc/testing.md
If we included ResourceQuota, we should keep it at the end of the
list to prevent incrementing quota usage prematurely.
```release-note
None
```
/cc @ayj
=> Updated admission controller order in test.

test/integration/testdata/initializer-configmap.yaml.tmpl
```release-note
NONE
```
/cc @ayj @ldemailly
=> Added DebugMode to initializer configmap.

adapter/config/crd/client.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1226
```release-note
```
=> Fix for missing CRD error message

platform/kube/inject/inject.go
```release-note
NONE
```
/cc @ayj
=> Updated log message for injectRequired.

test/integration/infra.go
=> RBAC delete ClusterRoleBindings

cmd/istioctl/inject.go
Partial fix for https://github.com/istio/istio/pull/743. This address issues (1) and (2) described by https://github.com/istio/pilot/issues/1246#issuecomment-328733384. 
The root cause for https://github.com/istio/istio/pull/743 was masked by multiple problems in error handling when the MeshConfig configmap read/decode failed. This PR address those issues but does not address the root cause which triggered them.
```release-note
```
=> fix error handling in configmap handling

platform/kube/inject/testdata/hello-ignore.yaml, platform/kube/inject/testdata/not-required.yaml
```release-note
NONE
```
/cc @ayj @rshriram
=> Updated annotation for `sidecar.istio.io/inject` in test case.

prow/pilot-coverage.sh
Currently cleaning up jobs that need access to cluster.
https://github.com/istio/test-infra/pull/488
```release-note
```
=> Code coverage does not need access to a cluster

test/integration/testdata/rbac-beta.yaml.tmpl
Use unique ClusterRole for shared clusters
=> Use unique ClusterRole for shared clusters

doc/testing.md
=> Recommend 1.7.5 for GKE and Minikube

model/config_test.go
=> Increase model coverage

bin/push-debian.sh, prow/pilot-postsubmit.sh, prow/pilot-presubmit.sh, tools/deb/BUILD
Add debian package creating as part of pre and postsubmit to enable CI for Raw VM
Properly automated generation of debian release artifact
```release-note
```
=> Creates debian package as part of CI

bin/init.sh, bin/upload-istioctl
Fixes https://github.com/istio/pilot/issues/
```release-note
none
```
=> Use bazel version of go

adapter/config/crd/BUILD, adapter/config/crd/config.go, adapter/config/crd/config_test.go, adapter/config/crd/conversion_test.go, adapter/config/ingress/BUILD, adapter/config/ingress/controller.go, adapter/config/ingress/controller_test.go, adapter/config/ingress/conversion_test.go, adapter/config/ingress/status.go, adapter/config/ingress/status_test.go, adapter/config/memory/controller.go, adapter/config/memory/monitor.go, adapter/config/memory/monitor_test.go, cmd/pilot-discovery/main.go, test/mock/config.go
More test coverage (#1233)
```release-note
```
=> Increase coverage in config adapters

test/integration/BUILD, test/integration/driver.go, test/integration/egress_rules.go, test/integration/testdata/egress-rule-google.yaml.tmpl, test/integration/testdata/egress-rule-httpbin.yaml.tmpl
Added tests for egress rules.
```NONE
```
=> Egress rules integration tests

WORKSPACE, istio.deps
=> Adds istio.deps for API

proxy/envoy/config.go
=> Reduce "unsupported UDP protocol" spam

cmd/istioctl/inject.go
Fixes https://github.com/istio/pilot/issues/1336
```release-note
```
=> bugfix: check error of GetMeshConfig in kube-inject

platform/consul/BUILD, platform/consul/controller_test.go, platform/consul/conversion_test.go, platform/consul/monitor_test.go
Improves code coverage for consul related files
```release-note
```
=> improved consul code coverage

cmd/istioctl/main.go
Changes istioctl to use the namespace for the current context in local kube config if it exists.
fixes istio/istio#979
Let me know if you think this is the right approach.
=> istioctl: Use namespace from kube config

cmd/pilot-agent/main.go, proxy/envoy/resources.go
**What this PR does / why we need it**: Eureka option was missing from proxy agent options.
```release-note
NONE
```
=> Add Eureka option to agent

adapter/config/ingress/status_test.go, test/eurekamirror/eurekamirror.go, test/integration/egress.go, test/integration/ingress.go
Just run `make fmt` 
```release-note
NONE
```
=> Updated fmt for pilot.

doc/build.md
```release-note
Pilot build requests 0.6.0 or later version of Bazel
```
=> Updated bazel version to 0.6.0 in build doc.

WORKSPACE, test/mixer/server.go
Istio/api renamed Attributes to CompressedAttributes.  Hence this change.
```release-note
```
=> Rename Attributes to CompressedAttributes

prow/pilot-e2e-smoketest.sh
=> pull istio/istio from release-0.2 for e2e

model/validation.go
Use the Golang net pkg functions to validate the correctness of IP addresses and CIDRs
```
NONE
```
=> Use the net packages to validate IP and CIDR correctness

README.md
=> add circle CI build status to readme

WORKSPACE, docker/Dockerfile.proxy, docker/Dockerfile.proxy_debug, istio.deps
This PR will be merged automatically once checks are successful.
```release-note
none
```
=> [DO NOT MERGE] Auto PR to update dependencies of pilot

.circleci/config.yml, bin/install-bazel.sh
Specify a version for minikube for the circleci tests
```release-note
NONE
```
=> put versions on minikube

prow/pilot-coverage.sh, prow/pilot-postsubmit.sh, prow/pilot-presubmit.sh
=> Support release-0.2 branch in old repo
