istio/old_pilot_repo

platform/kube/client.go
platform/kube/controller.go
platform/kube/minikube_test.go
test/mocks.go

Kubernetes controllers should not rely on strong consistency of the config registry.
Added tests to validate some work flows on using cache + event handling together.

Cache consistency tests and validation

---

cmd/main.go
example/echo/Dockerfile-envoy
example/echo/Dockerfile-manager
example/echo/build.sh
example/echo/echo.yaml
example/echo/server_config.pb.txt
model/controller.go
platform/kube/controller.go
platform/kube/minikube_test.go
proxy/envoy/BUILD
proxy/envoy/agent.go
proxy/envoy/config.go
proxy/envoy/resources.go
proxy/envoy/watcher.go

Complete the proxy supervising process basic implementation.
In this configuration, proxy container has a watcher process that watches for changes to CDS and triggers a hot-reload in Envoy. The watcher creates an Envoy config file from CDS service definitions and inserts a reference to another manager instance acting as SDS.
Eventually, once CDS API is available, we do not need the hot reload. Hot reload would still be necessary for RDS or anything else that's not captured by Envoy runtime APIs.

Add proxy watcher and auto-configuration for Envoy

---

model/service.go
model/service_test.go
model/validation.go
platform/kube/controller.go

This PR defines service tag as a label selector (`map[string]string`).
The code to compute endpoints for a service tag will be in a follow-up PR.

Define service tags

---

cmd/manager/BUILD
cmd/manager/config.go
cmd/manager/main.go
model/BUILD
model/conversion.go
model/registry.go
platform/kube/BUILD
platform/kube/client.go
platform/kube/controller.go
platform/kube/conversion.go

Example:  
```
> cat example
dst_service_name: test
> cat example | bazel-bin/cmd/manager/manager config put route-rule  test  -c ~/.kube/config 
> manager config list route-rule -c ~/.kube/config 
Kind route-rule, Name: test, Namespace: default
======
dstservicename: test
routerule: null
```

Introduce a CLI for configuration registry

---

WORKSPACE

Bazel 0.4.4 breaks the build with an error like this:
ERROR: .../external/io_bazel_rules_go/go/toolchain/BUILD:20:1: no such package '@io_bazel_rules_go_toolchain//': Not a file: ...external/golang_linux_amd64/BUILD and referenced by '@io_bazel_rules_go//go/toolchain:go_root'.
This commit rolls back the rules to 0.4.3, similar to what has been done for the mixer.

Update to rules_go latest commit

---

cmd/manager/main.go
proxy/envoy/BUILD
proxy/envoy/config.go
proxy/envoy/watcher.go

Modifies the watcher to update the Envoy config on changes to the proxy config definition.
This is a duplicate of #87 , with fixes to satisfy the linter. Just to get me going. :)
This has already been approved.

Propagate proxy config to generator

---

README.md
WORKSPACE

Now that my PR got merged into coreos/pkg, we're good to go.

Update bazel and rules_go to latest to enable mac build

---

model/proxy/alphav1/config/cfg.proto

Goal: 
- remove all mentions of clusters, tags, "source"
- align with existing service model.

Routing proto revision

---

WORKSPACE
test/integration/BUILD
test/integration/driver.go

Run all of the integration test's client requests in parallel. The downside to this approach (as-is) is the logs are harder to read since requests are interleaved. 
I'm also seeing that it takes a lot of request attempts (i.e. kube execs) before the test completes, but this seems to be a problem with the serialized version as well. 
```
2017/02/10 17:44:53 Making a request http://a/a from a (attempt 0)...
2017/02/10 17:44:53 kubectl exec a-3909435095-0c4fw -n istio-integration-1797x -c app client http://a/a
2017/02/10 17:44:54 Url=http://a/a
2017/02/11 01:44:54 Get http://a/a: dial tcp 10.19.252.162:80: getsockopt: connection refused
```

Parallelize the integration test's client requests

---

Jenkinsfile
cmd/manager/main.go
proxy/envoy/agent.go
proxy/envoy/config.go
proxy/envoy/watcher.go
test/integration/driver.go
test/integration/http-service-versions.yaml.tmpl
test/integration/http-service.yaml.tmpl
test/integration/manager.yaml.tmpl

- uses downward api to propagate pod names
- rename CLI commands: server => discovery, proxy => proxy sidecar
- decrease drain time to 30s
- print test logs in jenkins

Implement service node and cluster for envoy

---

test/integration/driver.go

Fix for issues/134. defer() isn't called from log.Fatal (i.e. os.Exit). Wrap the main test
function in a helper function so deferred functions can be triggered
on errors properly.

Cleanup namespaces properly when e2e test fails

---

Jenkinsfile
WORKSPACE
proxy/envoy/agent.go
test/integration/BUILD
test/integration/driver.go
test/integration/http-service-versions.yaml.tmpl
test/integration/http-service.yaml.tmpl
test/integration/manager.yaml.tmpl

I suspect we have a starvation issue where controllers overload some resource. This should reduce the load by limiting watchers to the test namespace.
Also fixed:
- marked driver.go manual to avoid building docker images automatically
- tried with recent envoy build and discovered it's broken for manager for unknown reason

Restrict tests to its namespace

---

test/integration/driver.go

Replaces the sleep inside the integration tests with Envoy restart epoch checks that wait until the epoch has been incremented.
Also re-enables fault tests, since this change should make them more reliable.

Remove sleeps in integration test

---

proxy/envoy/ingress.go
proxy/envoy/resources.go

A complementary fix to #150/#160, where inbound service proxy expects the host header on incoming requests to match the local pods IP / service hostname.
For the ingress controller case, the host header is either set by the client (to a virtual host name != service host name) and forwarded as-is; or set by the Envoy ingress controller to the local host.
This PR utilizes Envoy's support for host rewrite (see [docs](https://lyft.github.io/envoy/docs/configuration/http_conn_man/route_config/route.html)) to set the host header to the target service host name.
Note: tested locally/manually to verify that I can hit a backend service exposed via an ingress.

Rewrite ingress traffic host header to destination service hostname

---

bin/e2e.sh
test/integration/driver.go
test/integration/mixer.yaml.tmpl

The current bin/e2e.sh script assumes the known good prebuilt mixer image is stored in the same hub as the manager images, i.e. gcr.io/istio-testing. This doesn't work if user specifies alternate docker hubs, e.g. docker.io.

Use fully qualified image name (FQIN) for known good mixer image flag

---

proxy/envoy/config.go
proxy/envoy/config_test.go
proxy/envoy/ingress.go
proxy/envoy/policy.go
proxy/envoy/resources.go
proxy/envoy/route.go

This should be a non-functional change that adds TCP network filter definitions. 
Next step is to update the config generation (e.g. buildOutboundFilters) to generate the listener and cluster structs for TCP routes, merge HTTP and TCP listener/clusters based on some order of precedence (e.g. HTTP always higher priority than TCP, use RouteRule precedence), and then update the integration test to test non-HTTP services.

Add envoy resource definitions for TCP network filters

---

bin/check.sh

This PR sets gometalinter to run a single linter at a time, instead of its default of 16 linters concurrently.
On my dev VM, this has improved its runtime duration to ~2:20 (instead of ~4:00), while greatly reducing its memory usage (no more OOMs, no memory leaks).
As a bonus, it prevents gometalinter from producing lint errors (varcheck/aligncheck) on stdlib code:
```
/usr/local/go/src/os/user/lookup.go:38:9:warning: undeclared name: listGroups (aligncheck)
/usr/local/go/src/os/user/lookup.go:9:9:warning: undeclared name: current (aligncheck)
/usr/local/go/src/os/user/lookup.go:15:9:warning: undeclared name: lookupUser (aligncheck)
/usr/local/go/src/os/user/lookup.go:21:9:warning: undeclared name: lookupUserId (aligncheck)
/usr/local/go/src/os/user/lookup.go:27:9:warning: undeclared …
```

Set gometalinter to run linters sequentially

---

proxy/envoy/ingress.go

A follow-up to #177, where the rewritten host header did not include the destination service port number.
This worked for services listening on port 80 (for which the inbound cluster can match on hostname only), but not for services listening on other ports (e.g., productpage:9080).

Rewrite ingress traffic host header to destination service hostname:port

---

docker/BUILD
docker/manager_docker.bzl

This is part of the effort to address https://github.com/istio/proxy/issues/121

add bazel macro to build docker image variants

---

WORKSPACE
docker/debug/Dockerfile
docker/debug/build-and-publish-debug-image.sh

- encode sha256 in filename to make it easier to support multiple base
image revisions.
- add dnsutils and netcat to debug base image

update debug base image

---

proxy/envoy/ingress.go
proxy/envoy/watcher.go

Modify Envoy watchers (both ingress and sidecar) to `reload()` Envoy with configuration based on initial state, instead of waiting for the first event to arrive from the controller.
Note that this is currently done synchronously (blocking), to avoid racing with controller events lurking around the corner. This can be improved once we switch to a mechanism where reloads are linearized (e.g., by a single goroutine reloader).
Fixes #220.

Initialize Envoy at watcher creation

---

proxy/envoy/config.go
proxy/envoy/route.go
proxy/envoy/testdata/envoy.json.golden
test/integration/app-proxy-manager-agent.yaml.tmpl
test/integration/app.yaml.tmpl
test/integration/driver.go
test/integration/reachability.go

Use existing HTTP server/client to verify TCP routing rules by setting
up k8s services with non-http port names (e.g. tcp, tcp-alternative).
This also fixes bug in inbound TCP route construction by adding
ServiceAddress:ServicePort and EndpointAddress:ServicePort in addition
to EndpointAddress:Port.

Add TCP routing checks to e2e integration test

---

Jenkinsfile

This will prevent breakage when we update the library.
Add a 15 minute timeout for e2e.

Sets Shared pipeline libs to fix version

---

bin/init.sh
bin/install-prereqs.sh
cmd/istioctl/BUILD
cmd/istioctl/istioctl_test.go
cmd/istioctl/main.go
doc/build-vagrant.md
doc/build.md
model/config_test.go
model/service.go
proxy/envoy/config.go
test/integration/app-proxy-manager-agent.yaml.tmpl
test/integration/driver.go

Treat HTTPS as opaque TCP traffic.
Build fixes:
* organize init scripts
* document go1.8 as a requirement
* start errors with lower case 
* fix istioctl test dependency

Support HTTPS

---

cmd/istioctl/istioctl_test.go
cmd/root.go

If $KUBECONFIG defined, use it for --kubeconfig.  Don't silently fail if --kubeconfig or $KUBECONFIG is invalid.

Use $KUBECONFIG in istioctl

---

docker/BUILD
docker/manager_docker.bzl

github.com/istio/manager/pull/197 inadvertently removed
istio_debug_proxy as a dependency for runtime_debug. Add a option to
specify per-image tars to the manager_docker_build rule so different
layers can be specified for release and debug docker targets.
ref https://github.com/istio/manager/issues/316

add per-image tar option to manager_docker_build

---

Jenkinsfile

Currently for postsubmit we also run the presubmit part. Modifying this
to limit postsubmit to:
- Code Coverage (To update the reference)
- Integrations tests
- Docker Push

Limit postsubmit action.

---

docker/prepare_proxy.sh
proxy/envoy/resources.go
proxy/envoy/testdata/envoy-fault.json.golden
proxy/envoy/testdata/envoy-v0.json.golden
proxy/envoy/testdata/envoy-v1.json.golden
test/integration/app-proxy-manager-agent.yaml.tmpl

- parametrize the script in preparation of using `configmap`s to store global configs
- change proxy port from 5001 to 15001 and admin port from 5000 to 15000 to prevent port collisions

Add init script parameters

---

cmd/manager/main.go
model/BUILD
model/secret.go
platform/kube/client.go
platform/kube/client_test.go
proxy/envoy/BUILD
proxy/envoy/ingress.go
test/integration/ingress-proxy.yaml.tmpl

Basic interface to access secrets to prevent the use of k8s library directly in the proxy config gen.
Also, fixes a couple of bugs with ingress: default namespace and retries.

Define secret registry

---

test/integration/driver.go
test/integration/reachability.go

Fix a bug that was failing the post-submit. Ingress should be deleted once, not at every iteration.

Keep ingress around

---

model/config_test.go
model/service.go
model/service_test.go
proxy/envoy/route.go
proxy/envoy/testdata/cds-circuit-breaker.json.golden
proxy/envoy/testdata/cds-ssl-context.json.golden
proxy/envoy/testdata/cds.json.golden
proxy/envoy/testdata/envoy-fault.json.golden
proxy/envoy/testdata/envoy-v0.json.golden
proxy/envoy/testdata/envoy-v1.json.golden
proxy/envoy/testdata/rds-fault.json.golden
proxy/envoy/testdata/rds-timeout.json.golden
proxy/envoy/testdata/rds-v0.json.golden
proxy/envoy/testdata/rds-v1.json.golden
proxy/envoy/testdata/rds-weighted.json.golden

Envoy is enforcing schema on cluster names and that means ":" is no longer allowed.

Change service encoding scheme to satisfy Envoy

---

proxy/envoy/config.go
proxy/envoy/config_test.go
proxy/envoy/discovery.go
proxy/envoy/ingress.go
proxy/envoy/policy.go
proxy/envoy/resources.go
proxy/envoy/route.go
proxy/envoy/testdata/cds-circuit-breaker.json.golden
proxy/envoy/testdata/cds-ssl-context.json.golden
proxy/envoy/testdata/cds.json.golden
proxy/envoy/testdata/envoy-fault.json.golden
proxy/envoy/testdata/envoy-v0.json.golden
proxy/envoy/testdata/envoy-v1.json.golden
proxy/envoy/testdata/rds-fault.json.golden
proxy/envoy/testdata/rds-timeout.json.golden
proxy/envoy/testdata/rds-v0.json.golden
proxy/envoy/testdata/rds-v1.json.golden
proxy/envoy/testdata/rds-weighted.json.golden
test/integration/driver.go

Change config generation to use three types of listeners:
1. inbound listeners, do not use CDS, RDS, SDS; bind to pod IP, port port pair.
2. outbound TCP listeners, use only SDS, bind to service IP, service port pair
3. outbound HTTP listeners, use CDS, RDS, SDS; bind to 0.0.0.0 and share ports
This PR touches a lot of cases, so please help reviewing this. This is needed to enable auth on inbound HTTP listeners.

Use IP address in the listeners

---

cmd/istioctl/inject.go
docker/prepare_proxy.sh
platform/kube/inject/inject.go
platform/kube/inject/inject_test.go
platform/kube/inject/refresh.sh
platform/kube/inject/testdata/enable-core-dump.yaml
platform/kube/inject/testdata/enable-core-dump.yaml.injected

Enable core dumps in the runtime proxy for better always-on debugging
experience. "sysctl -w kernel.core_pattern=/tmp/core.%e.%p.%t"
requires additional privileges so use separate init-container to avoid
leaking elevated privileges into non-debug files/images.
This commit adds the `--coreDump` flag to control whether core dumps
are enabled or not and defaults to true for pre-alpha development.

istioctl: add option to enable core dumps in injected runtime proxy

---

cmd/manager/main.go
platform/kube/controller.go
platform/kube/controller_test.go

This PR adds two flags to the ingress controller (`manager ingress` command):
- `--ingress_class="istio"` - The class of ingress resources to be processed by the ingress controller.
- `--default_ingress_controller=true` - Specifies whether running as the cluster's default ingress controller, thereby processing unclassified ingress resources.
Implementation note: the user-facing `--default_ingress_controller` flag is represented internally as an `IngressSyncMode=Off|Strict|Default` enum parameter which is passed down into the `kube.Controller`. The `Off` value disables ingress watching/processing altogether, and is used by the `manager sidecar` and `manager discovery` commands.
Resolves #371

Enhanced ingress class annotation processing

---

platform/kube/inject/testdata/auth.cert-dir.yaml.injected
platform/kube/inject/testdata/auth.non-default-service-account.yaml
platform/kube/inject/testdata/auth.non-default-service-account.yaml.injected
platform/kube/inject/testdata/auth.yaml
platform/kube/inject/testdata/auth.yaml.injected
platform/kube/inject/testdata/enable-core-dump.yaml
platform/kube/inject/testdata/enable-core-dump.yaml.injected
platform/kube/inject/testdata/frontend.yaml
platform/kube/inject/testdata/frontend.yaml.injected
platform/kube/inject/testdata/hello-ignore.yaml
platform/kube/inject/testdata/hello-ignore.yaml.injected
platform/kube/inject/testdata/hello-multi.yaml
platform/kube/inject/testdata/hello-multi.yaml.injected
platform/kube/inject/testdata/hello.yaml
platform/kube/inject/testdata/hello.yaml.injected
platform/kube/inject/testdata/multi-init.yaml
platform/kube/inject/testdata/multi-init.yaml.injected

These files are for unit tests and should not be actually deployed, so
using `fake.docker.io` instead of an actuall docker repo.

Change gcr.io to fake.docker.io

---

cmd/manager/main.go

This is to stay consistent with the options for `istioctl kube-inject`

Rename CLI option for manager from --config to --meshConfig

---

test/integration/mixer.yaml.tmpl

This shouldn't be merged until the manager codebase starts using a mixer image from 3/30 or later.

update config to match latest mixer config

---

cmd/istioctl/inject.go
platform/kube/inject/inject.go
platform/kube/inject/inject_test.go

Let MANAGER_HUB and MANAGER_TAG env vars override defaults in inject.go if present
These variables are defined in _istio/istio/istio.VERSION_.
See issue #469

Let MANAGER_HUB and MANAGER_TAG env vars override defaults

---

docker/prepare_proxy.sh

Previously for loopback traffic the iptables rule routed it as:
app -> proxy -> app
This will route it as:
app -> proxy (client-side) -> proxy (server-side) -> app
So proxy can upgrade the protocol between proxies (e.g. HTTP/2, TLS)
cc @myidpt @kyessenov 
Closes #103 .

Fix loopback issue injecting istio proxy

---

Jenkinsfile
bin/get_workspace_status

The builds done with Jenkins were marked as dirty. The reason was that we update the tools/bazel.rc with the content of tools/bazel.rc.jenkins. Version stable-70699be of fixes that. Update pipeline to build istioctl first.

Fix get_workspace_status for Jenkins

---

cmd/manager/main.go
proxy/context.go
proxy/envoy/config.go
proxy/envoy/config_test.go
proxy/envoy/policy.go
proxy/envoy/resources.go
proxy/envoy/testdata/envoy-fault.json.golden
proxy/envoy/testdata/envoy-v0-auth.json.golden
proxy/envoy/testdata/envoy-v0.json.golden
proxy/envoy/testdata/envoy-v1-auth.json.golden
proxy/envoy/testdata/envoy-v1.json.golden

- remove `source.service`
- add `source.uid` and `target.uid` to be kubernetes pod name, namespace custom URI
- add `source.ip` and `target.ip` to be proxy IPs
Reference #489

Update mixer filter config

---

Jenkinsfile
bin/get_workspace_status

Jenkins was saving artifacts to a location using SHA or tag if tag was available. In https://github.com/istio/istio-testing/commit/cd138c4c8e915880eecb95d68950be171c477c0a, we are only using tag when specified. Using this version of library.
Tweaking get_workspace_status for branches.

Only using tag when explicity asked

---

Jenkinsfile

A few *_debug images were removed as part of
https://github.com/istio/manager/pull/563/files#diff-8458c56b8c783101a48aebedb12d119bR91.
So update Jenkins file accordingly.

Stop Jenkins from pushing non-existent docker images

---

model/BUILD
platform/kube/BUILD
platform/kube/client.go

Add "gcp" and "oidc" auth plugins. Verified that "gcp" plugin works for GKE. We still want to use client certs for testing since bazel does not allow invoking random commands from tests.

Add k8s auth plugins

---

test/integration/ingress.go

Ensures ingress status is given an IP. Since we are running without `mesh.ingressService` set, the IP will be the node IP.

e2e ingress status IP check

---

BUILD
test/server/echo.go

This is a re-write of the ?codes= injection feature from last week.
The echo server output includes its hostname
If a request to the echo server HTTP includes ?codes=code[:chances],... the server might send a response other than HTTP 200.  This is for testing code that retries, but where we don't need to track the exact number of retries.
For example, ?codes=500:90,200:10 returns 500 90% of times and 200 10% of times
For example, ?codes=500:1,200:1 returns 500 50% of times and 200 50% of times
For example, ?codes=501:999,401:1 returns 500 99.9% of times and 401 0.1% of times.
For example, ?codes=500,200 returns 500 50% of times and 200 50% of times

New ?codes= option to simulate HTTP errors from echo server

---

apiserver/apiserver.go
cmd/manager/main.go
test/integration/BUILD
test/integration/apiserver.go
test/integration/driver.go
test/integration/testdata/manager.yaml.tmpl

First part of fix for #660 
driver.go will issue requests against apiserver and verify the responses are as expected.
Allow API server to run outside K8s with KUBECONFIG env.  Test template should include apiserver container
A future PR will add additional tests so istioctl create/get/put/delete is used as well.
driver.go now takes an argument to just run one test.  I have been testing with
```
./test/integration/integration --tag vagrant_20170504_192054 -hub docker.io/esnible \
--testtype "apiserver" --auth disable
```

e2e test for API server.

---

test/integration/testdata/zipkin.yaml

Accidentally leftover from manual testing.

Remove NodePort from Zipkin service definition in integration tests

---

cmd/istioctl/main.go
cmd/istioctl/mixer.go

Display the names of positional arguments when they are not specified.

Usage for positional subcommands

---

BUILD
bin/get_workspace_status
cmd/istioctl/inject.go
cmd/version/BUILD
cmd/version/version.go
kube-inject-versions

Introduce a new file 'kube-inject-versions` to set the hardcoded
default hub and tag info for kube-inject. Order of precedence is flag,
env-var, and then built-in defaults.
Existing documentation that use `source istio.VERSION` should continue
to work until istio.VERSION is phased out.
For debug purposes `istioctl version --kube-inject` shows the default
docker hub and tag. This flag is hidden from help text to avoid
confusing users as kube-inject is planned to be moved server-side
post-alpha.

istioctl: compile in default hub and tag versions for kube-inject

---

platform/kube/ingressstatus.go

Make the ingress election ID more unique to reduce the chance of conflicts with other ingress controllers. Currently the election ID is the same as many other ingress controllers, which means the Istio ingress controller is competing with other controllers.

Make ingress election ID more unique

---

platform/kube/client.go

The `istioctl version` currently fails to print the remote apiserver version.  It prints the local version, then "Error: the server could not find the requested resource".  This fixes that bug.

Allow istioctl version to work w/o --kube=false

---

proxy/envoy/config.go
proxy/envoy/discovery_test.go
proxy/envoy/ingress.go
proxy/envoy/route.go
proxy/envoy/testdata/all-rds.json.golden
proxy/envoy/testdata/envoy-fault.json.golden
proxy/envoy/testdata/envoy-v0-auth.json.golden
proxy/envoy/testdata/envoy-v0.json.golden
proxy/envoy/testdata/envoy-v1-auth.json.golden
proxy/envoy/testdata/envoy-v1.json.golden
proxy/envoy/testdata/rds-ingress-ssl.json.golden
proxy/envoy/testdata/rds-ingress-weighted.json.golden
proxy/envoy/testdata/rds-ingress.json.golden
proxy/envoy/testdata/rds-v0-status.json.golden

Relaxation on the authority field values used for routing:
- inbound HTTP listeners will not require the host matches the service name
- outbound HTTP listeners will not require colon + port suffix
- ingress proxy does not override authority header
Ref https://github.com/istio/issues/issues/8
Ref #791

Relaxation on host values used by routing

---

proxy/envoy/config.go
proxy/envoy/egress.go
proxy/envoy/ingress.go
proxy/envoy/resources.go
proxy/envoy/testdata/envoy-ingress.json.golden
test/integration/ingress.go

Enable updating `x-forwarded-for` on the ingress proxy.
The sidecar proxy passes the header unmodified (documented in Envoy and validated with a test).
cc @saturnism

use_remote_address for ingress

---

WORKSPACE
cmd/cmd.go
model/validation.go
model/validation_test.go
proxy/envoy/BUILD
proxy/envoy/config.go
proxy/envoy/config_test.go
proxy/envoy/egress.go
proxy/envoy/ingress.go
proxy/envoy/resolve.go
proxy/envoy/resources.go
proxy/envoy/testdata/envoy-egress-auth.json.golden
proxy/envoy/testdata/envoy-egress.json.golden
proxy/envoy/testdata/envoy-fault.json.golden
proxy/envoy/testdata/envoy-ingress.json.golden
proxy/envoy/testdata/envoy-v0-auth.json.golden
proxy/envoy/testdata/envoy-v0.json.golden
proxy/envoy/testdata/envoy-v1-auth.json.golden
proxy/envoy/testdata/envoy-v1.json.golden
proxy/envoy/watcher.go

The goal of this PR is to enable collection of proxy stats. This PR focuses on generating envoy configs to direct statsd output.
This PR updates the proxy agent and the manager to support a new field in the mesh config: `statsd_udp_address`. The initial default option is to generate this address from the IP address of Mixer and the configured statsd-udp port (defaults to 9125).
Tested on new deployments. A PR to istio/istio that updates the deployment configs for mixer, pilot, and prometheus will follow.
This has a current weakness: if mixer service is deleted and restarted, export will stop working, as the `statsd_udp_address` is not regenerated in response.

Add support for statsd export

---

WORKSPACE
bin/gazelle

This update is to fix Gazelle performance issues when fetching `k8s.io/ingress`
Not sure whats going on with the gazelle file.
Signed-off-by: Liam White <liamwhite@uk.ibm.com>

Update workspace to new bazel_rules_go to fix gazelle performance

---

BUILD
WORKSPACE
adapter/config/memory/BUILD
adapter/config/memory/config_test.go
adapter/config/tpr/client_test.go
adapter/config/tpr/controller_test.go
adapter/config/tpr/conversion.go
bin/get_workspace_status
bin/init.sh
codecov.requirement
kube-inject-versions
model/BUILD
model/config.go
model/config_test.go
model/validation.go
model/validation_test.go
test/mock/BUILD
test/mock/config.go
tools/version/BUILD

Also: fix minor defects:
- simplify redundant code to allocate test namespaces
- retrieve destination policy by key instead of iterating over objects

Increase test coverage of config store

---

Jenkinsfile

Create and use new the codecov repository upload token for the Pilot repo. The codecov credential PILOT_CODECOV_TOKEN  has already been created in Jenkins. This PR updates the Jenkinsfile to use it as part of pre/post submit.
Fixes https://github.com/istio/pilot/issues/857

Update codecov token

---

adapter/config/aggregate/BUILD
adapter/config/aggregate/config.go
adapter/config/aggregate/config_test.go
adapter/config/memory/config_test.go
model/BUILD

A subsequent PR will add:
- in-memory cache controller (implementation of `ConfigStoreCache`)
- separate ingress bits from TPR and aggregate over the two stores in the main config store

Implement store aggregator

---

proxy/envoy/ingress.go
proxy/envoy/resolve.go

Filter out non-HTTP ingress ports. This should fix the Envoy crashing observed in https://github.com/istio/issues/issues/20. Instead, Pilot will log a warning.

Filter ingress ports

---

model/config.go

This fixes #895
User issue: https://github.com/istio/issues/issues/38
This fix is made and tested against the release-0.1 branch. Corresponding fix needs to be made in master and the question is do we want to release this fix in a new alpha driver (0.1.x) or are we going to only fix it in 0.2.x? If we decide to put out another 0.1.x, we should also provide some kind of interim fix for the rbac issue that several people are complaining about (https://github.com/istio/istio/pull/333)

fix match rule discarded from ingress routes

---

platform/kube/inject/inject.go
platform/kube/inject/testdata/auth.cert-dir.yaml.injected
platform/kube/inject/testdata/auth.non-default-service-account.yaml.injected
platform/kube/inject/testdata/auth.yaml.injected
platform/kube/inject/testdata/enable-core-dump.yaml.injected
platform/kube/inject/testdata/frontend.yaml.injected
platform/kube/inject/testdata/hello-config-map-name.yaml.injected
platform/kube/inject/testdata/hello-multi.yaml.injected
platform/kube/inject/testdata/hello-probes.yaml.injected
platform/kube/inject/testdata/hello.yaml.injected
platform/kube/inject/testdata/multi-init.yaml.injected

Commit https://github.com/istio/pilot/pull/921 on behalf of @bjartek.   
Add `privileged=true` to init-containers to unblock deployments with SELINUX (e.g. OpenShift). As @bjartek suggested in his original PR, this is functionally sufficient, but longer term someone needs to sort through what exact permissions are needed with SELinux and add the necessary RBAC rules to OpenShift similar to what what it is for Kubernetes in the main repo.
Fixes istio/issues#34

added priviledged=true to the init container and to all tests

---

Jenkinsfile

As we did before at presubmit, now we want like to collect data from postsubmit. Theoretically, they should be the same, but we would like to figure it out. And if so, we will only keep one of them.

Publish coverage at postsubmit as well

---

prow/pilot-presubmit.sh

Attempting to make codecov not report CI failed as it is currently doing.

prow: add more env variables to codecov

---

Jenkinsfile
bin/upload-istioctl
prow/pilot-postsubmit.sh
prow/pilot-presubmit.sh

- Simplifying Jenkins
- Enabling OSX and Windows istioctl builds for postsubmit and release artifacts

Enabling back windows istioctl build for postsubmit only

---

bin/upload-istioctl

For some reason this was not needed when running locally, but it is need in Prow.

Add mousetrap for windows.

---

bin/get_workspace_status
cmd/istioctl/inject.go

0.1.x releases have that dangerous setting of using 0.1 instead of 0.1.x for proxy and init images
fixing this (with the assumption that the correct -tag is passed for test/dev per @sebastienvas )

Shouldn't have hardcoded 0.1 (or any 2 digit) tags

---

Makefile

this config is linked, but not forcefully linked, during setup.
```
[vbatts@getdown] (master) ~/src/github.com/istio/pilot$ make
ln: failed to create symbolic link 'platform/kube/config': File exists
make: *** [Makefile:19: setup] Error 1
```
With this, a user could put their own config without getting clobbered,
or no error on `make` when the PHONY setup runs everytime.
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

Makefile: proper deps for the setup target

---

proxy/envoy/resources.go
proxy/envoy/route.go
proxy/envoy/route_test.go
proxy/envoy/testdata/lds-v0-fault-auth.json.golden
proxy/envoy/testdata/lds-v0-none-auth.json.golden
proxy/envoy/testdata/lds-v0-weighted-auth.json.golden
proxy/envoy/testdata/lds-v1-fault-auth.json.golden
proxy/envoy/testdata/lds-v1-none-auth.json.golden
proxy/envoy/testdata/lds-v1-weighted-auth.json.golden

Fixes #1002 
This fix causes pilot to configure Envoy to check client certificates on upstream proxy listeners.

Set require_client_certificate in SSL context

---

prow/pilot-e2e-smoketest.sh

This will fix the issue of missing logs for e2e smoke test

Export var such to be used in child script

---

Makefile

```release-note
None
```
Fixed https://github.com/istio/pilot/issues/1072

Enabled setup install pre-requested go binaries.

---

Makefile

```release-note
None
```
Fixed https://github.com/istio/pilot/issues/1073

Enabled code coverage test in Makefile.

---

.github/PULL_REQUEST_TEMPLATE.md

Added more content for PULL_REQUEST_TEMPLATE.

---

bin/upload-istioctl

Fixes breakage of upload-istioctl when the build directory is a symlink.
```release-note
Fix failure on cross-compiled istioctl builds when path contains a symlink
```

Use absolute name of PWD to match Bazel's behavior

---

Makefile
doc/build.md

```release-note
None
```
Updated build doc to use `make` but not `bazel` which is more simple to use.

Updated build doc to use `make` but not `bazel`.

---

bin/build_pilot_release.yaml
bin/release.sh

Add config to run Pilot release on GCB
```release-note
Add release.sh script that runs tasks that currently exist as part of the Jenkins config.
Add a config file for running Pilot release builds on Google Container Builder.
```

Add release script to build Pilot artifacts

---

WORKSPACE
proxy/envoy/config.go
proxy/envoy/discovery.go
proxy/envoy/discovery_test.go
proxy/envoy/egress.go
proxy/envoy/ingress.go
proxy/envoy/resources.go
proxy/envoy/testdata/envoy.json.golden
proxy/envoy/testdata/lds-httpproxy.json.golden
proxy/envoy/testdata/rds-httpproxy.json.golden
test/integration/infra.go

Adds HTTP routes on a dedicated HTTP proxy port for non-transparent addressing. Also, makes iptables method optional, and admin port optional.
```release-note
HTTP proxy support for client-side routing.
```

HTTP Proxy implementation

---

bin/release.sh
platform/kube/conversion.go

Last part of the release automation with Google Container Builder. 
Extract credentials from KMS and push to docker.io.
```release-note
NONE
```

Enable KMS and update docker and storage for release

---

bin/push-docker

The current local tag format is `$(whoami)_$(date +%y%m%d_%h%m%s)`.
It seems the intention was to have the date as year, month, day, hour, minute, second. However, %h is a shortened month name like Aug, and %m is month. This way, month appears three time in the tag, for no reason. The correct format is %H for hours, %M for minutes and %S for seconds.
```release-note
NONE
```

fix format of the local tag in bin/push-docker

---

test/client/client.go
test/grpcecho/echo.proto
test/server/echo.go

Revert renaming of Echo gRPC service to GrpcEcho service (as some piece of s**t is caching old pb.go files and refusing to flush the cache).
```release-note
NONE
```

revert GrpcEcho -> Echo

---

test/integration/driver.go

Also make the `--mixer` and `--ca` CLI options consistent. Previously
`--mixer` takes the full docker image URI but `--ca` only accepts an
image tag. After this PR, both options take the full docker image URI.
```
NONE
```
/cc @andraxylia 
/cc @wattli 
/cc @kyessenov

Update the CA docker image used for e2e test

---

platform/kube/conversion.go
platform/kube/conversion_test.go

Fix the bug that when no service account is specified in annotation, empty service accounts are returned.

---

Makefile

Today, running `make setup` twice fails due to an attempt to create platform/kube/config (soft link), while it already exists. 
```NONE
```

in make setup: do not create platform/kube/config if it already exists

---

model/config.go
model/config_test.go
proxy/envoy/config.go

Prevent conflicting egress rules from causing envoy to crash.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1166
```
```

Reject egress rules that conflict on some domain

---

bin/gobuild-and-push-nobazel

It helps a lot when you develop from Mac and hit issues with Bazel.
Make sure you run dep ensure first to bring vendor dependencies.
```release-note
```

Script to build using plain go from MAC (no bazel needed)

---

bin/gocompile-and-push-images

Bazelify wrongly belived a file called gobuild is a bazel build file.

Rename gobuild script to gocompile to avoid bazelify horror

---

cmd/pilot-agent/BUILD
cmd/pilot-agent/main.go
model/BUILD
proxy/agent.go
proxy/agent_test.go
proxy/envoy/discovery.go
proxy/envoy/watcher.go
proxy/envoy/watcher_test.go
test/mock/BUILD

add a flag to override "istio-proxy" as service cluster
```release-note
Exposes Envoy service-cluster and binarypath options to the proxy agent, allowing customizations.
```

Customize service cluster

---

WORKSPACE
model/config.go
model/config_test.go
model/validation.go
model/validation_test.go
proxy/envoy/config.go
test/mock/config.go

Implements handling egress rules according to the new format - one domain, using IstioService for destination
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1180
```
```

implementation of egress rules with one domain

---

cmd/pilot-discovery/main.go

Pilot currently uses 1 second resync period which puts additional load
on apiserver. This is not necessary and doesn't scale well in shared
test clusters. Increase to 60 seconds for now with the possibility of
further increases if this doesn't cause test instability.
See
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-api-machinery/PbSCXdLDno0/v9gH3HXVDAAJ
for recommendations on setting resync period.
```release-note
```

Increase default ResyncPeriod from 1 to 60 seconds

---

bin/get_workspace_status

Change the default version used by kube-inject to be the full SHA

---

istio.deps

Postsubmit jobs of Proxy are still on Jenkins and fast forwarding stable branch was suspended. Use Proxy master branch to update pilot instead.
```release-note
None
```

Use pilot master instead of stable

---

prow/pilot-e2e-smoketest.sh

```release-note
none
```
As decided, we are switching to use rbac-auth as e2e-gate

Use rbac+auth e2e

---

WORKSPACE
cmd/pilot-agent/main.go
proxy/context.go
proxy/envoy/watcher.go
proxy/envoy/watcher_test.go

This PR adds an optional --availabilityZone flag to pilot-agent (which gets translated into --service-zone flag for Envoy). This lets the end user specify the availability zone associated with an envoy instance during startup time. It is possible to dynamically infer this from kubernetes, but it will bloat the pilot agent binary (40Mb+). If the flag is not specified, the service-zone flag will not be passed (this is the default for backward compatibility).
When injecting the pod from initializer or kube-inject, this flag will not be specified (and az aware routing will thus remain disabled). However, users wishing to manually inject the sidecar can specify the flag to take advantage of Envoy's az-aware routing.
**Which issue this PR fixes** …

adding --service-zone flag to Envoy

---

doc/build.md

as 0.5.2 doesn't work, hit the following:  
root@linsvm:~/workspace/src/istio.io/pilot# ./bin/init.sh 
++ pwd
+ PDIR=/root/workspace/src/istio.io/pilot
+ '[' /root/workspace/src/istio.io/pilot '!=' /root/workspace/src/istio.io/pilot ']'
+ bazel build //...
ERROR: /root/workspace/src/istio.io/pilot/test/grpcecho/BUILD:4:1: no such package '@com_github_google_protobuf//': Error downloading [https://github.com/google/protobuf/archive/v3.2.0.tar.gz] to /root/.cache/bazel/_bazel_root/1f24f37de2c6e5f62ca533b368d79765/external/com_github_google_protobuf/v3.2.0.tar.gz: Checksum was a839d3f1519ff9d68ab908de5a0f269650ef1fc501c10f6eefd4cae51d29b86f but wanted 2a25c2b71c707c5552ec9afdfb22532a93a339e1ca5d38f163fe4107af08c54c and referenced by '//test/grpcecho:go_default_library_protos'.
ERROR: …

pilot - update to bazel version 0.5.3 or later

---

cmd/BUILD
cmd/cmd.go
platform/kube/inject/BUILD
platform/kube/inject/configmap.go
proxy/BUILD
proxy/context.go
proxy/context_test.go

`ProxyConfig` defaults are not applied properly to user defined configuration. The current code applies defaults by decoding the user supplied MeshConfig YAML into a MeshConfig protobuf with expected default values. This works for top-level fields in the protobuf but breaks with nested pointer types, i.e. `ProxyConfig`. 
The fix implemented here uses the same strategy but explicitly applies it to the nested ProxyConfig after the top-level configuration is decoded.
```release-note
```

Make sure ProxyConfig defaults are applied

---

platform/kube/inject/inject.go
proxy/envoy/config.go
proxy/envoy/egress.go
proxy/envoy/ingress.go
proxy/envoy/mixer.go
proxy/envoy/testdata/lds-egress-auth.json.golden
proxy/envoy/testdata/lds-egress.json.golden
proxy/envoy/testdata/lds-httpproxy.json.golden
proxy/envoy/testdata/lds-ingress.json.golden
proxy/envoy/testdata/lds-v0-fault-auth.json.golden
proxy/envoy/testdata/lds-v0-fault.json.golden
proxy/envoy/testdata/lds-v0-none-auth.json.golden
proxy/envoy/testdata/lds-v0-none.json.golden
proxy/envoy/testdata/lds-v0-weighted-auth.json.golden
proxy/envoy/testdata/lds-v0-weighted.json.golden
proxy/envoy/testdata/lds-v1-fault-auth.json.golden
proxy/envoy/testdata/lds-v1-fault.json.golden
proxy/envoy/testdata/lds-v1-none-auth.json.golden
proxy/envoy/testdata/lds-v1-none.json.golden
proxy/envoy/testdata/lds-v1-weighted-auth.json.golden
proxy/envoy/testdata/lds-v1-weighted.json.golden
proxy/envoy/testdata/lds-websocket.json.golden
proxy/envoy/testdata/rds-egress.json.golden
proxy/envoy/testdata/rds-ingress-ssl.json.golden
proxy/envoy/testdata/rds-ingress-weighted.json.golden
proxy/envoy/testdata/rds-ingress.json.golden
test/integration/driver.go

Rename the last vestiges of target.* attributes in Pilot, now that Mixer has support for destination.* attributes. Also, since proxy supports fine grained mixer_check/mixer_report attributes, enable those instead of coarse grained mixer_control flag. Mixer_check can be disabled globally by the user using DisablePolicyCheck flag.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1227 
```release-note
Ability to turn of mixer policy checks independent of mixer metrics reports.
```

Mixer filter: rename target->destination, and use mixer_check, mixer_report options

---

WORKSPACE

The checksum of  https://github.com/google/protobuf/archive/v3.2.0.tar.gz changed under us. Probably because protobuf team rebuilt the package.
It seems it happened before 
https://github.com/google/protobuf/issues/3087
```release-note
```

Updating protobuf archive checksum

---

model/config.go
proxy/envoy/config.go
proxy/envoy/config_test.go
proxy/envoy/discovery_test.go
proxy/envoy/policy.go
proxy/envoy/route.go
proxy/envoy/testdata/cds-circuit-breaker.json.golden
proxy/envoy/testdata/cds-ssl-context.json.golden
proxy/envoy/testdata/egress-rule-cb-policy.yaml.golden
proxy/envoy/testdata/egress-rule-timeout-route-rule.yaml.golden
proxy/envoy/testdata/rds-httpproxy.json.golden
proxy/envoy/testdata/rds-timeout.json.golden
proxy/envoy/testdata/rds-v0-nomixer.json.golden

Enable routing and destination policies for egress rules
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1180 
```release-note
NONE
```
Its not correct. The goldens are not getting updated properly, even though all the clusters are being added to the common pool. Worse still, running the refresh goldens command, updates the circuit breaker settings for world service!

Egress routing fix

---

adapter/config/crd/client.go
adapter/config/crd/conversion.go
adapter/config/crd/conversion_test.go
adapter/config/crd/generate.sh
cmd/istioctl/BUILD
cmd/istioctl/main.go
platform/kube/BUILD

Teach istioctl non-hyphenated resource names for proxy CRD types, e.g. `istioctl get routerules`.
fixes https://github.com/istio/pilot/issues/1236
Question: support for hyphenated names is still retained. Shall we remove that to avoid being stuck with multiple naming variants? 
```release-note
```

teach istioctl non-hyphenated resource names

---

doc/testing.md

RBAC will be enabled in minikube starting from version 0.22.2.
The current instructions are misleading - RBAC is not yet enabled in minikube. It will be enabled in version 0.22.2, and an additional flag will be required - see https://github.com/kubernetes/minikube/pull/1970#issuecomment-329984008 and https://github.com/kubernetes/kubernetes/issues/52487.
```NONE
```

added instructions about RBAC in minikube

---

test/util/kubernetes.go

90 pod retry budget is not enough for my setting. I run minikube on top of VirtualBox on my MacBook Pro 2.5 GHz Intel Core i7, 16 GB 1600 MHz DDR3.
@andraxylia @ijsnellf This is resubmission of #1296, which was incorrectly rebased. Sorry for the confusion
```NONE
```

increase pod check budget from 90 to 200

---

platform/kube/inject/initializer.go
platform/kube/inject/inject.go

istio-system namespace is handled differently than normal user
namespaces and should not have sidecar's injected. This fixes a bug in
that logic where the sidecar was not injected (correct) but the
pending list of initializers was not cleared (bug). This caused
istio-system components to not be deployed in cluster-wide
installations to istio-system name.
```release-note
```

bugfix: remove istio initializer from istio-system workloads

---

test/integration/egress.go

in countries other than US, www.google.com redirects to local versions
of google e.g. www.google.co.il, www.google.de etc.
**Which issue this PR fixes** *(optional, in `fixes 
this redirection fails the egress test. cloud.google.com does not redirect and works OK outside of US
#<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
```NONE
```

use cloud.google.com instead of www.google.com in egress test

---

adapter/config/ingress/conversion.go
proxy/envoy/header.go
proxy/envoy/header_test.go
proxy/envoy/resources.go

Reverts istio/pilot#1291 until it's ready and safe to introduce to the release branch.

Revert "Use regex field instead of overloading header match for regex routes"

---

bin/release.sh
bin/use_bazel_go.sh

Fixes issue in use_bazel_go.sh for release.
Fixes #1310 
Changed the script to be a little more robust such that we can test it locally. Cloud Builder checks out code in /workspace, use_bazel_go assumes the codes is checked out in a pilot directory which is not true. Even so we run the build from the GOPATH, bazel will use the link target to create a bazel-workspace directory.
```release-note
none
```

Make release script runnable locally

---

bin/use_bazel_go.sh

As @kyessenov suggested this is less error prone.
```release-note
none
```

Simplify use_bazel_go with bazel info

---

cmd/istioctl/BUILD
cmd/istioctl/main.go

adds `config-create` command to istioctl.  Components of istio require a kubeconfig file.  To run istio in environment other than kubernetes, user would need to install and use `kubectl` to generate this file.  The new command creates/modifies the kubeconfig file so `kubectl` is not needed for non-k8s environments.  Uses k8s libraries for generation and writing to file
```release-note
```

Context-create command for istioctl

---

proxy/agent.go
proxy/agent_test.go

The last change to the logic to abort-all envoys introduced a scenario when envoy could dead lock on rapid config changes (as is possible with firing config scheduling for the same config too often as done by the cert watcher).
This fixes the case by always reconciling on any error (abort or not). The reconciliation logic will apply in case the current config aborts immediately after reconciliation.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1329 
```release-note
```

Fix proxy agent lock-up

---

adapter/config/crd/conversion.go
adapter/config/crd/conversion_test.go

Sometimes empty content can be in the input file(s) for istioctl and such empty config data can result in
errors, since istioctl doesn't know how to handle such data. They should be skipped.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1351
```release-note
none
```

skip empty objects for the input files of istioctl commands

---

bin/check.sh
proxy/envoy/watcher.go
proxy/envoy/watcher_test.go

File watcher waits for maxDelay duration to deliver notification to updatefunc().
Current file watcher passes all events from fsnotify up to the agent. 
This can (and has) cause excessive event generation.
It can also cause related events to be processed separately. For example cert and key file change events may be delivered separately even though they change together.
This is related to pr #1331 
```release-note
NONE
```

Add dampening to file watcher. It will only deliver 1 event per maxDelay

---

test/integration/testdata/eureka.yaml.tmpl

Removes `NodePort` designation from Eureka service. This might cause issues with the automated tests if it is not removed. Fortunately, no Eureka tests have been enabled yet, so it shouldn't be causing issues right now.
```release-note
NONE
```

remove nodeport from eureka service

---

platform/kube/inject/inject.go
platform/kube/inject/testdata/auth.cert-dir.yaml.injected
platform/kube/inject/testdata/auth.non-default-service-account.yaml.injected
platform/kube/inject/testdata/auth.yaml.injected
platform/kube/inject/testdata/daemonset.yaml.injected
platform/kube/inject/testdata/enable-core-dump.yaml.injected
platform/kube/inject/testdata/frontend.yaml.injected
platform/kube/inject/testdata/hello-always.yaml.injected
platform/kube/inject/testdata/hello-config-map-name.yaml.injected
platform/kube/inject/testdata/hello-multi.yaml.injected
platform/kube/inject/testdata/hello-never.yaml.injected
platform/kube/inject/testdata/hello-probes.yaml.injected
platform/kube/inject/testdata/hello.yaml.injected
platform/kube/inject/testdata/multi-init.yaml.injected
platform/kube/inject/testdata/replicaset.yaml.injected
platform/kube/inject/testdata/replicationcontroller.yaml.injected
platform/kube/inject/testdata/statefulset.yaml.injected

Currently all trace spans generated by Istio proxied services are associated with the name 'istio-proxy'. This is confusing for end users, with the only indication of what services are being called, being the operation name which provides the hostname being called.
This PR enables the Deployment template's 'app' label value (if present) to be used as the service name.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: This PR outlines the issue as well as providing a potential fix.
The [istio service cluster configuration](https://github.com/istio/api/blob/master/proxy/v1/config/proxy_mesh.proto#L30-L42) comment …

tracing: Provide a more meaningful service name in traces

---

platform/kube/cache.go

PodCache has no mutex protecting its internal state. Add RWMutex to fix this.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1377 
```release-note
Fix race in Pilot PodCache
```

add locking to pod cache

---

adapter/config/ingress/conversion.go
cmd/pilot-agent/main.go
proxy/envoy/config.go
proxy/envoy/ingress.go
proxy/envoy/testdata/rds-ingress-weighted.json.golden
proxy/envoy/testdata/rds-ingress.json.golden

Some drive by bug fixes (attach port to the vhost so that requests with port can also be matched), use ingress instances when filtering routes, so that route rules can be scoped to ingress only.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/istio/issues/issues/87
https://github.com/istio/issues/issues/60
```release-note
Ingress will allow port numbers in the authority header
```

Ingress bug fixes

---

bin/gocompile-and-push-images.sh

**What this PR does / why we need it**: Eureka mirror was missing from part of the `gocompile-and-push-images.sh` script
```release-note
NONE
```

Fix eurekamirror build in `gocompile-and-push-images.sh` script

---

platform/kube/inject/inject.go
platform/kube/inject/inject_test.go
platform/kube/inject/testdata/hello-host-network.yaml
platform/kube/inject/testdata/hello-host-network.yaml.injected

PR for https://github.com/istio/istio.github.io/issues/655, see #655 for details
```release-note
When a pod uses hostNetwork: true, the pod will be disabled from side car injection on purpose because we don't want the envoy side car to change the network configuration at the host level.
```

fix for istio-initializer needs to ignore hostNetwork pod specs

---

proxy/context.go
proxy/envoy/config.go
proxy/envoy/config_test.go
proxy/envoy/discovery_test.go
proxy/envoy/testdata/cds-circuit-breaker.json.golden
proxy/envoy/testdata/cds-ingress.json.golden
proxy/envoy/testdata/cds-istio-egress.json.golden
proxy/envoy/testdata/cds-router.json.golden
proxy/envoy/testdata/cds-ssl-context.json.golden
proxy/envoy/testdata/envoy.json.golden
proxy/envoy/testdata/lds-router-auth.json.golden
proxy/envoy/testdata/lds-router.json.golden
proxy/envoy/testdata/rds-router-weighted.json.golden
test/mock/service.go

Ingress is a generic concept applicable across platforms. K8S has ingress as first class resource (except its broken in several ways). In non k8s platforms, we cannot use this ingress resource spec reliably, as it requires enabling ingress controller without the status syncer (adds more complexities), especially if people are just adding it for the dummy ingress.
This PR defines a new proxy agent mode (LB) that allows the sidecar to obtain just outbound configs, and run as standalone envoy [which becomes ingress in Consul/Eureka]. With this, we would no longer have to expose services directly (like the way we do today). An added benefit is that this would allow people to run envoy as standalone using load balancer service in kubernetes, with support …

Enable ingress mode for Eureka/Consul

---

platform/kube/inject/inject.go
platform/kube/inject/inject_test.go
platform/kube/inject/testdata/hello-host-network.yaml
platform/kube/inject/testdata/hello-host-network.yaml.injected

Automatic merge from submit-queue
fix for istio-initializer needs to ignore hostNetwork pod specs
PR for https://github.com/istio/istio.github.io/issues/655, see #655 for details
```release-note
When a pod uses hostNetwork: true, the pod will be disabled from side car injection on purpose because we don't want the envoy side car to change the network configuration at the host level.
```
This is the same PR but for 0.2 release branch.

fix for istio-initializer needs to ignore hostNetwork pod specs (#1440)

---

WORKSPACE

**What this PR does / why we need it**: addresses a couple of issues that fail the build when updating bazel to 0.6.0
**Which issue this PR fixes*:
fixes:
```shell
[vbatts@getdown] (master) ~/src/istio.io/pilot$ bazel build //...
ERROR: /home/vbatts/.cache/bazel/_bazel_vbatts/4cef8fba7ce23e923fa298b99fb665e8/external/io_bazel_rules_go/go/private/binary.bzl:226:48: name 'lib' is not defined (did you mean 'libs'?).
ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors.
INFO: Elapsed time: 1.107s
```
and
```shell
[vbatts@getdown] {master *} ~/src/istio.io/pilot$ bazel build //...
ERROR: /home/vbatts/src/github.com/istio/pilot/WORKSPACE:452:1: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'com_github_google_protobuf').
ERROR: …
```

update for bazel 0.6.0

---

adapter/config/crd/conversion.go

The crd client code uses the object namespace in rest
calls. Kubernetes expects this namespace to be non-empty. Add the
"default" namespace when the namespace is omitted during model-to-crd
conversion to satisfy this condition.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1472 
```release-note
NONE
```

fix `Error: an empty namespace may not be set during creation` bug

---

model/validation.go

extract validateCIDR() for further use in other validations
just a refactoring, to use validateCIDR() in other validations, e.g. to validate egress rules for TCP CIDR
```release-note
NONE
```

refactor ValidateIPv4Subnet()

---

cmd/pilot-agent/main.go

Handling errors first is consistent with the other binaries

Invert error handling

---

cmd/istioctl/main.go

Updated example test on `istioctl`.
Fixes this `istioctl` command output:
```
$ istioctl 
Istio configuration command line utility.
Create, list, modify, and delete configuration resources in the Istio
system.
Available routing and traffic management configuration types:
[route-rule ingress-rule egress-rule destination-policy]
```
The routing and traffic management types should now be hyphen-less as per rest of CLI. 
**Which issue this PR fixes** 
None 
```
NONE
```

fix: remove hyphens from istioctl types help text 

---

cmd/istioctl/main.go

https://github.com/istio/issues/issues/110 reminds me that istioctl
can set empty namespace for mixer configs, which will be delivered
directly and therefore it can cause same error of "empty namespace".
When the obtained namespace happens to be empty, I think it should
return the default value.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1637
```release-note
none
```

let getDefaultNamespace() returns "default" if nothing is found.
